my_builder_cronos:
  exporter:
    key: unique-key
    mailto: your@email.com
    path: /bin:/usr/local/bin
    executor: /usr/bin/php
    console: /var/www/html/webshake/bin/console
    shell: /bin/bash